HAL_SRCS := \
	hal/src/hal.c

HAL_INCLUDES := \
	-Ihal/include

HAL_LIB  := $(BUILD_DIR)/libopencomm_hal.a
HAL_OBJS := $(HAL_SRCS:%.c=$(OBJ_DIR)/%.o)

include hal/version.mk
OPENCOMM_HAL_VER = $(OPENCOMM_HAL_VER_MAJ).$(OPENCOMM_HAL_VER_MIN).$(OPENCOMM_HAL_VER_PATCH)
ifdef OPENCOMM_HAL_VER_PRERELEASE
OPENCOMM_HAL_VER := $(OPENCOMM_HAL_VERSION)-$(OPENCOMM_HAL_VER_PRERELEASE)
endif


$(HAL_LIB)-$(OPENCOMM_HAL_VER): $(HAL_OBJS)
	mkdir -p $(BUILD_DIR)
	$(AR) $(ARFLAGS) $@ $^

INCLUDES += $(HAL_INCLUDES)

CPPFLAGS += \
	-DOPENCOM_HAL_VER=\"$(OPENCOMM_HAL_VER)\"

LIB_TARGETS += $(HAL_LIB)-$(OPENCOMM_HAL_VER)
